### ISSUE TITLE
Error: Error in variable_classes[[v$name]] : subscript out of bounds

### ISSUE THREAD

**Issue by JoepvanderPlas** [grantmcdermott/etwfe#24]
When I follow the vignette and run the function emfx, I get the following error: Error in variable_classes[[v$name]] : subscript out of bounds

**Comment by grantmcdermott** [comment]
Which version of the package, etc? Please post your `sessionInfo()`

**Comment by JoepvanderPlas** [comment]
I am using version 0.3.0

**Comment by grantmcdermott** [comment]
Again, please post your `sessionInfo()` result.

Did you update marginaleffects recently? If so, there are some breaking changes that are fixed in the dev version. (A new CRAN submission is coming soon.) Can you try the dev version and see if the problem persists?

```r
install.packages("etwfe", repos = "https://grantmcdermott.r-universe.dev")
```

Please restart your R session too.

**Comment by vincentarelbundock** [comment]
This is à `marginaleffects` error. I would also like to be sure that this is using the latest of both packages. If so, I'd love to see a simple replicable example using public data.

**Comment by grantmcdermott** [comment]
🎉
